name: Create Rally Defect
on: 
  issues:
    types: opened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "building"
  create_defect:
    name: Create Defect
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Updating Defect with title '$TITLE', body '$DEFECT_BODY', and state '$STATE'"
        env:
          TITLE: ${{ github.event.issue.title }}
          DEFECT_BODY: ${{ github.event.issue.body }}
          STATE: ${{ github.event.issue.state }}