name: "Create Rally Defect"
on: 
  issues:
    types: opened
jobs:
  create_defect:
    name: Create Defect
    runs-on: ubuntu-latest
    steps:
      - run: echo "Creating Defect with title '$TITLE' and body '$DEFECT_BODY'"
      - env:
        TITLE: {{ github.event.issues.title }}
        DEFECT_BODY: {{ github.event.issues.body }}